name: Lighthouse

on:
  pull_request:
    branches: main

  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Run Lighthouse Tests
        uses: treosh/lighthouse-ci-action@v8
        with:
          configPath: ./.lighthouserc.js
          uploadArtifacts: true
          temporaryPublicStorage: true
