name: Lighthouse

on:
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          configPath: ./.lighthouserc.js
          uploadArtifacts: true
          temporaryPublicStorage: true
